---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-webapp
  annotations:
    service.kubernetes.io/topology-mode: auto
spec:
  type: {{ .Values.service.type }}
  selector:
    app: webapp
    release: {{ .Release.Name }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: web