---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: zap
        release: {{ .Release.Name }}
        rev: !!string {{ .Release.Revision }}
    spec:
      containers:
      - name: apache
        image: {{ .Values.apache.image.repository}}:{{ .Values.apache.image.tag }}
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: httpd
          mountPath: "/usr/local/apache2/conf"
      - name: zap
        image: {{ .Values.zap.image.repository}}:{{ .Values.zap.image.tag }}
        resources:
          requests:
            memory: 4Gi
            cpu: 2
        args:
        - /zap/script/zap-exec.sh
        env:
        - name: PORT
          value: "8085"
        - name: HOST
          value: "0.0.0.0"
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: zap-api-key
              key: api_key
        volumeMounts:
        - name: zapexec
          mountPath: "/zap/script"
      volumes:
      - name: httpd
        configMap:
          name: httpd
          defaultMode: 0644
      - name: zapexec
        configMap:
          name: zap-exec
          defaultMode: 0755